### ISSUE TITLE
Node Tree view buggy

### ISSUE THREAD

**Issue by Sciss** [Sciss/ScalaColliderSwing#19]
In GitLab by @Sciss on Feb 3, 2021, 13:51

Doesn't catch new nodes, forgets freed nodes etc. It's fundamentally broken when it comes to dynamic updates.

**Comment by Sciss** [comment]
In GitLab by @Sciss on Feb 3, 2021, 13:53

e.g.
```
java.lang.IllegalStateException: This tuple is no longer valid. It has been deleted from its table
	at prefuse.data.tuple.TableTuple.validityCheck(TableTuple.java:77)
	at prefuse.data.tuple.TableTuple.get(TableTuple.java:141)
	at de.sciss.synth.swing.j.JNodeTreePanel.removeChild(JNodeTreePanel.scala:396)
	at de.sciss.synth.swing.j.JNodeTreePanel.deleteChild(JNodeTreePanel.scala:380)
	at de.sciss.synth.swing.j.JNodeTreePanel.$anonfun$nlRemoveNode$2(JNodeTreePanel.scala:449)
	at de.sciss.synth.swing.j.JNodeTreePanel.de$sciss$synth$swing$j$JNodeTreePanel$$visDo(JNodeTreePanel.scala:534)
	at de.sciss.synth.swing.j.JNodeTreePanel.$anonfun$nlRemoveNode$1(JNodeTreePanel.scala:449)
	at de.sciss.synth.swing.j.JNodeTreePanel.$anonfun$nlRemoveNode$1$adapted(JNodeTreePanel.scala:448)
	at scala.Option.foreach(Option.scala:437)
	at de.sciss.synth.swing.j.JNodeTreePanel.de$sciss$synth$swing$j$JNodeTreePanel$$nlRemoveNode(JNodeTreePanel.scala:448)
	at de.sciss.synth.swing.j.JNodeTreePanel$$anonfun$1.$anonfun$applyOrElse$3(JNodeTreePanel.scala:126)
	at de.sciss.synth.swing.j.JNodeTreePanel$$anon$5.run(JNodeTreePanel.scala:348)

```
and
```
Feb 03, 2021 1:53:36 PM prefuse.action.ActionList run
WARNING: null
java.lang.NullPointerException
	at de.sciss.synth.swing.impl.DynamicTreeLayout.getParams(DynamicTreeLayout.scala:436)
	at de.sciss.synth.swing.impl.DynamicTreeLayout.apportion(DynamicTreeLayout.scala:323)
	at de.sciss.synth.swing.impl.DynamicTreeLayout.firstWalk(DynamicTreeLayout.scala:270)
	at de.sciss.synth.swing.impl.DynamicTreeLayout.run(DynamicTreeLayout.scala:204)
	at prefuse.action.ActionList.run(ActionList.java:79)
	at prefuse.action.Action.run(Action.java:122)
	at prefuse.activity.Activity.runActivity(Activity.java:152)
	at prefuse.activity.ActivityManager.run(ActivityManager.java:365)

```
