### ISSUE TITLE
ScalaColliderSwing-2.6.4 on Debian Bookworm

### ISSUE THREAD

**Issue by rd--** [Sciss/ScalaColliderSwing#21]
Hello,

I'm trying to setup ScalaColliderSwing-2.6.4 and getting the message below.

This is on `Linux x1 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`.

I've tried with `openjdk-17-jre` and `openjdk-11-jre` and with both the .zip and .deb files.

I think I've done the same things as last time, when it worked, but that was on a different computer and with the previous version (1.14.7, I've tried that here as well and it doesn't start either).

Any hints?  I imagine it's something obvious but I don't know anything about Java I'm afraid.

Thanks kindly.

````
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
        at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:832)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
        at com.thoughtworks.xstream.XStream.<init>(XStream.java:392)
        at com.alee.utils.XmlUtils.initializeXStream(XmlUtils.java:128)
        at com.alee.utils.XmlUtils.getXStream(XmlUtils.java:106)
        at de.sciss.submin.Submin.install(Submin.java:29)
        at de.sciss.synth.swing.Prefs$LookAndFeel$Light$.install(Prefs.scala:53)
        at de.sciss.synth.swing.Main$.init(Main.scala:360)
        at de.sciss.desktop.impl.SwingApplicationImpl.$anonfun$main$1(ApplicationImpl.scala:61)
        at scala.swing.Swing$$anon$1.run(Swing.scala:39)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @75ea7af9
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.thoughtworks.xstream.core.util.Fields.locate(Fields.java:40)
        at com.thoughtworks.xstream.converters.collections.TreeMapConverter.<clinit>(TreeMapConverter.java:50)
        ... 26 more
````

**Comment by Sciss** [comment]
This sounds indeed like a JDK issue - the longer term solution is to update the Web Look and Feel (it's on my list of things), but in the meantime, OpenJDK 11 should actually be fine. Can you verify you selected OpenJDK 11 as default, i.e. using `sudo update-java-alternatives --list` to see the installed versions, and `sudo update-java-alternatives -s java-1.11.0-openjdk-amd64` (or similar) to change. What does `java -version` report?

**Comment by Sciss** [comment]
Another workaround could be to edit the preferences and change the look-and-feel. In `~/.java/.userPrefs/de/sciss/synth/swing/prefs.xml`, find the line `<entry key="look-and-feel" value="light"/>` (or `dark`), and change to `<entry key="look-and-feel" value="metal"/>`. Add the entry if it does not exist.

**Comment by rd--** [comment]
Your're correct, of course, and it does work with v.11!  I'm sorry for troubling you.  Many thanks for the help.

For anyone finding this, I'd ended up with:

`openjdk-11-jre openjdk-11-jre-headless openjdk-17-jre-headless`

and that won't work (i.e. `apt remove openjdk-17-jre` and `apt install openjdk-11-jre` won't necessarily go from 17 to 11).

Removing the last of these fixes things.

**Comment by Sciss** [comment]
Note that you do not have to uninstall OpenJDK 17 - use `update-java-alternatives` to switch between the different installations.
